import Button from '@components/Button';
import Head from 'next/head';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center w-full bg-gray-300">
        Hey
        <Button />
      </main>
    </div>
  );
};

export default Home;
